### ISSUE TITLE
fleek apply fails when using a different user than the one that installed nix, even though nix-shell works

### ISSUE THREAD

**Issue by lamarios** [ublue-os/fleek#151]
**Describe the bug**
did setup nix and nix-shell following the instructions (on silverblue using[ the script i](https://github.com/dnkmmr69420/nix-with-selinux/blob/main/silverblue-installer.sh)n the README)

did
```
fleek init
fleek add k9s
fleek apply
```
then got the following error:
```
fleek apply --debug --verbose
 [d]  debug enabled
 [i]  Loaded configuration
 [d]  git autopush: false
 [d]  git autocommit: false
 [d]  git autopull: false
 [*]  Apply fleek configuration
 [v]  Initializing templates
 [d]  skipping git
 [✓]  Writing configuration files                                                                                  
 [d]  skipping git
  ERROR                                                                                                            
  ERROR   Error: package exists in fleek and nix profile                                                           
  ERROR                                                                                                            
 [d]                                                                                                               
      ExecutionID:8c19bbf9e7044f79a2d98e3f8efa5d4e
```

**To Reproduce**

**Expected behavior**

k9s to be available via command line

**Environment**
 - OS: fedora silverblue (custom image built on top of ublue)
 - Shell: zsh
 - fleek version: 0.8.5

**Additional context**

Things to note:
 nix was installed with user id: 1000 and fleek works fine
 the user where it fails is id: 1002

nix-shell -p k9s works as expected

fleek.yml
```
aliases:
    fleeks: cd /var/home/xendit/.local/share/fleek
bling: none
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
name: Fleek Configuration
packages:
  - helix
  - k9s
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: x86_64
      hostname: yoga7
      os: linux
      username: xendit
unfree: true

```
