### ISSUE TITLE
Applying configuration after git push, hangs?

### ISSUE THREAD

**Issue by mcdent** [ublue-os/fleek#160]
I have setup the git config to sync from a new install of fleek. However when I do the `fleek apply`
it just seems to hang and not sure when it will finish? Maybe trying to install some packages?
```
❯ fleek apply
 [d]  debug enabled
 [d]  git autopush: true
 [d]  git autocommit: true
 [d]  git autopull: true
 [*]  Apply fleek configuration
 [d]  is git repo
 [d]  git will pull
From github.com:user_name_removed/fleek
 * branch            main       -> FETCH_HEAD
 [✓]  Writing configuration files                                                                                        
 [d]  is git repo
 [d]  git will add
 [d]  git will commit
 [d]  git status is empty, skipping commit
 [d]  git will push
Everything up-to-date
Applying configuration (just spins)
```
Config in .fleek.yaml is
```
 cat .fleek.yml
aliases:
    fleeks: cd /home/mike/.local/share/fleek
bling: default
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true 
    autopush: true 
    enabled: true 
name: Fleek Configuration
packages:
    - helix
    - nerdfonts
    - neo
    - difftastic
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: docker1
      os: linux
       cat .fleek.yml
aliases:
    fleeks: cd /home/mike/.local/share/fleek
bling: default
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true 
    autopush: true 
    enabled: true 
name: Fleek Configuration
packages:
    - helix
    - nerdfonts
    - neo
    - difftastic
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: docker1
      os: linux
      username: mike
    - arch: x86_64
      hostname: thinkpad
      os: linux
      username: mike
unfree: true
username: mike
    - arch: x86_64
      hostname: thinkpad
      os: linux
      username: mike
unfree: true
```

hopefully relevant lines from ps -ef
```
mike       17413   16154  0 10:41 pts/0    00:00:00 nix build .#homeConfigurations."mike@thinkpad".activationPackage --out-link /tmp/home-manager-build.kBOT2LdmC1/generation
root       17422    5559  1 10:41 ?        00:00:13 nix-daemon 17413
nixbld1    18163   17422  0 10:56 ?        00:00:00 bash -e /nix/store/57620l1168piiia2bmmsxxhh7sjb2n40-builder.sh
nixbld1    18172   18163 12 10:56 ?        00:00:03 curl --location --max-redirs 20 --retry 3 --disable-epsv --cookie-jar cookies --user-agent curl/8.0.1 Nixpkgs/23.05 --insecure -C - --fail https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/VictorMono.zip --output /nix/store/frfg13dfmcmarc4il8zyzqsly192d8zw-VictorMono.zip
mike       18188    2066  0 10:56 ?        00:00:00 /usr/libexec/gnome-control-center-search-provider
```
